// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: api/mykratos/v1/m.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMRequest) Reset() {
	*x = CreateMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMRequest) ProtoMessage() {}

func (x *CreateMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMRequest.ProtoReflect.Descriptor instead.
func (*CreateMRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{0}
}

type CreateMReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateMReply) Reset() {
	*x = CreateMReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMReply) ProtoMessage() {}

func (x *CreateMReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMReply.ProtoReflect.Descriptor instead.
func (*CreateMReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{1}
}

type UpdateMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMRequest) Reset() {
	*x = UpdateMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMRequest) ProtoMessage() {}

func (x *UpdateMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMRequest.ProtoReflect.Descriptor instead.
func (*UpdateMRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{2}
}

type UpdateMReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMReply) Reset() {
	*x = UpdateMReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMReply) ProtoMessage() {}

func (x *UpdateMReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMReply.ProtoReflect.Descriptor instead.
func (*UpdateMReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{3}
}

type DeleteMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMRequest) Reset() {
	*x = DeleteMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMRequest) ProtoMessage() {}

func (x *DeleteMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMRequest.ProtoReflect.Descriptor instead.
func (*DeleteMRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{4}
}

type DeleteMReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMReply) Reset() {
	*x = DeleteMReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMReply) ProtoMessage() {}

func (x *DeleteMReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMReply.ProtoReflect.Descriptor instead.
func (*DeleteMReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{5}
}

type GetMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMRequest) Reset() {
	*x = GetMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMRequest) ProtoMessage() {}

func (x *GetMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMRequest.ProtoReflect.Descriptor instead.
func (*GetMRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{6}
}

type GetMReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMReply) Reset() {
	*x = GetMReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMReply) ProtoMessage() {}

func (x *GetMReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMReply.ProtoReflect.Descriptor instead.
func (*GetMReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{7}
}

type ListMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMRequest) Reset() {
	*x = ListMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMRequest) ProtoMessage() {}

func (x *ListMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMRequest.ProtoReflect.Descriptor instead.
func (*ListMRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{8}
}

type ListMReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMReply) Reset() {
	*x = ListMReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_m_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMReply) ProtoMessage() {}

func (x *ListMReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_m_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMReply.ProtoReflect.Descriptor instead.
func (*ListMReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_m_proto_rawDescGZIP(), []int{9}
}

var File_api_mykratos_v1_m_proto protoreflect.FileDescriptor

var file_api_mykratos_v1_m_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0d,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xe8, 0x03, 0x0a, 0x01, 0x4d, 0x12, 0x61,
	0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x22, 0x0e, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x12, 0x61, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x10, 0x1a, 0x0e, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x12, 0x61, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x12,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x2a, 0x0e, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x12, 0x58, 0x0a, 0x04, 0x47, 0x65, 0x74, 0x4d, 0x12,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x12, 0x0e, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x6d, 0x12, 0x60, 0x0a, 0x05, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x13,
	0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x2f, 0x6c,
	0x69, 0x73, 0x74, 0x42, 0x30, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73,
	0x2d, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mykratos_v1_m_proto_rawDescOnce sync.Once
	file_api_mykratos_v1_m_proto_rawDescData = file_api_mykratos_v1_m_proto_rawDesc
)

func file_api_mykratos_v1_m_proto_rawDescGZIP() []byte {
	file_api_mykratos_v1_m_proto_rawDescOnce.Do(func() {
		file_api_mykratos_v1_m_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mykratos_v1_m_proto_rawDescData)
	})
	return file_api_mykratos_v1_m_proto_rawDescData
}

var file_api_mykratos_v1_m_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_mykratos_v1_m_proto_goTypes = []interface{}{
	(*CreateMRequest)(nil), // 0: api.mykratos.v1.CreateMRequest
	(*CreateMReply)(nil),   // 1: api.mykratos.v1.CreateMReply
	(*UpdateMRequest)(nil), // 2: api.mykratos.v1.UpdateMRequest
	(*UpdateMReply)(nil),   // 3: api.mykratos.v1.UpdateMReply
	(*DeleteMRequest)(nil), // 4: api.mykratos.v1.DeleteMRequest
	(*DeleteMReply)(nil),   // 5: api.mykratos.v1.DeleteMReply
	(*GetMRequest)(nil),    // 6: api.mykratos.v1.GetMRequest
	(*GetMReply)(nil),      // 7: api.mykratos.v1.GetMReply
	(*ListMRequest)(nil),   // 8: api.mykratos.v1.ListMRequest
	(*ListMReply)(nil),     // 9: api.mykratos.v1.ListMReply
}
var file_api_mykratos_v1_m_proto_depIdxs = []int32{
	0, // 0: api.mykratos.v1.M.CreateM:input_type -> api.mykratos.v1.CreateMRequest
	2, // 1: api.mykratos.v1.M.UpdateM:input_type -> api.mykratos.v1.UpdateMRequest
	4, // 2: api.mykratos.v1.M.DeleteM:input_type -> api.mykratos.v1.DeleteMRequest
	6, // 3: api.mykratos.v1.M.GetM:input_type -> api.mykratos.v1.GetMRequest
	8, // 4: api.mykratos.v1.M.ListM:input_type -> api.mykratos.v1.ListMRequest
	1, // 5: api.mykratos.v1.M.CreateM:output_type -> api.mykratos.v1.CreateMReply
	3, // 6: api.mykratos.v1.M.UpdateM:output_type -> api.mykratos.v1.UpdateMReply
	5, // 7: api.mykratos.v1.M.DeleteM:output_type -> api.mykratos.v1.DeleteMReply
	7, // 8: api.mykratos.v1.M.GetM:output_type -> api.mykratos.v1.GetMReply
	9, // 9: api.mykratos.v1.M.ListM:output_type -> api.mykratos.v1.ListMReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_mykratos_v1_m_proto_init() }
func file_api_mykratos_v1_m_proto_init() {
	if File_api_mykratos_v1_m_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mykratos_v1_m_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_m_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mykratos_v1_m_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mykratos_v1_m_proto_goTypes,
		DependencyIndexes: file_api_mykratos_v1_m_proto_depIdxs,
		MessageInfos:      file_api_mykratos_v1_m_proto_msgTypes,
	}.Build()
	File_api_mykratos_v1_m_proto = out.File
	file_api_mykratos_v1_m_proto_rawDesc = nil
	file_api_mykratos_v1_m_proto_goTypes = nil
	file_api_mykratos_v1_m_proto_depIdxs = nil
}
