// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: api/mykratos/v1/my.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MyContent) Reset() {
	*x = MyContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyContent) ProtoMessage() {}

func (x *MyContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyContent.ProtoReflect.Descriptor instead.
func (*MyContent) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{0}
}

func (x *MyContent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MyContent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateMyRequest) Reset() {
	*x = CreateMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMyRequest) ProtoMessage() {}

func (x *CreateMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMyRequest.ProtoReflect.Descriptor instead.
func (*CreateMyRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateMyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyContent *MyContent `protobuf:"bytes,1,opt,name=MyContent,proto3" json:"MyContent,omitempty"`
}

func (x *CreateMyReply) Reset() {
	*x = CreateMyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMyReply) ProtoMessage() {}

func (x *CreateMyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMyReply.ProtoReflect.Descriptor instead.
func (*CreateMyReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMyReply) GetMyContent() *MyContent {
	if x != nil {
		return x.MyContent
	}
	return nil
}

type UpdateMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateMyRequest) Reset() {
	*x = UpdateMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyRequest) ProtoMessage() {}

func (x *UpdateMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateMyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyContent *MyContent `protobuf:"bytes,1,opt,name=MyContent,proto3" json:"MyContent,omitempty"`
}

func (x *UpdateMyReply) Reset() {
	*x = UpdateMyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyReply) ProtoMessage() {}

func (x *UpdateMyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyReply.ProtoReflect.Descriptor instead.
func (*UpdateMyReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMyReply) GetMyContent() *MyContent {
	if x != nil {
		return x.MyContent
	}
	return nil
}

type DeleteMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMyRequest) Reset() {
	*x = DeleteMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyRequest) ProtoMessage() {}

func (x *DeleteMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyRequest.ProtoReflect.Descriptor instead.
func (*DeleteMyRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMyReply) Reset() {
	*x = DeleteMyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMyReply) ProtoMessage() {}

func (x *DeleteMyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMyReply.ProtoReflect.Descriptor instead.
func (*DeleteMyReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{6}
}

type GetMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMyRequest) Reset() {
	*x = GetMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRequest) ProtoMessage() {}

func (x *GetMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRequest.ProtoReflect.Descriptor instead.
func (*GetMyRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{7}
}

func (x *GetMyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyContent *MyContent `protobuf:"bytes,1,opt,name=MyContent,proto3" json:"MyContent,omitempty"`
}

func (x *GetMyReply) Reset() {
	*x = GetMyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReply) ProtoMessage() {}

func (x *GetMyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReply.ProtoReflect.Descriptor instead.
func (*GetMyReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{8}
}

func (x *GetMyReply) GetMyContent() *MyContent {
	if x != nil {
		return x.MyContent
	}
	return nil
}

type ListMyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMyRequest) Reset() {
	*x = ListMyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRequest) ProtoMessage() {}

func (x *ListMyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRequest.ProtoReflect.Descriptor instead.
func (*ListMyRequest) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{9}
}

type ListMyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*MyContent `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ListMyReply) Reset() {
	*x = ListMyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mykratos_v1_my_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyReply) ProtoMessage() {}

func (x *ListMyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mykratos_v1_my_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyReply.ProtoReflect.Descriptor instead.
func (*ListMyReply) Descriptor() ([]byte, []int) {
	return file_api_mykratos_v1_my_proto_rawDescGZIP(), []int{10}
}

func (x *ListMyReply) GetResults() []*MyContent {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_mykratos_v1_my_proto protoreflect.FileDescriptor

var file_api_mykratos_v1_my_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x09, 0x4d, 0x79, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x49, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x35, 0x0a, 0x0f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79,
	0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x21,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x1e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x46, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x38, 0x0a, 0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x09, 0x4d, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x79,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x32, 0xe0, 0x03, 0x0a, 0x02, 0x4d, 0x79, 0x12, 0x5f, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x79, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x3a, 0x01, 0x2a,
	0x22, 0x06, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x12, 0x64, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x79, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b,
	0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x3a, 0x01,
	0x2a, 0x1a, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x61,
	0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0d, 0x2a, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x12, 0x58, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x56, 0x0a, 0x06, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x79, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72,
	0x61, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x76, 0x31,
	0x2f, 0x6d, 0x79, 0x42, 0x30, 0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x79, 0x6b, 0x72, 0x61,
	0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73,
	0x2d, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x79, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mykratos_v1_my_proto_rawDescOnce sync.Once
	file_api_mykratos_v1_my_proto_rawDescData = file_api_mykratos_v1_my_proto_rawDesc
)

func file_api_mykratos_v1_my_proto_rawDescGZIP() []byte {
	file_api_mykratos_v1_my_proto_rawDescOnce.Do(func() {
		file_api_mykratos_v1_my_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mykratos_v1_my_proto_rawDescData)
	})
	return file_api_mykratos_v1_my_proto_rawDescData
}

var file_api_mykratos_v1_my_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_mykratos_v1_my_proto_goTypes = []interface{}{
	(*MyContent)(nil),       // 0: api.mykratos.v1.MyContent
	(*CreateMyRequest)(nil), // 1: api.mykratos.v1.CreateMyRequest
	(*CreateMyReply)(nil),   // 2: api.mykratos.v1.CreateMyReply
	(*UpdateMyRequest)(nil), // 3: api.mykratos.v1.UpdateMyRequest
	(*UpdateMyReply)(nil),   // 4: api.mykratos.v1.UpdateMyReply
	(*DeleteMyRequest)(nil), // 5: api.mykratos.v1.DeleteMyRequest
	(*DeleteMyReply)(nil),   // 6: api.mykratos.v1.DeleteMyReply
	(*GetMyRequest)(nil),    // 7: api.mykratos.v1.GetMyRequest
	(*GetMyReply)(nil),      // 8: api.mykratos.v1.GetMyReply
	(*ListMyRequest)(nil),   // 9: api.mykratos.v1.ListMyRequest
	(*ListMyReply)(nil),     // 10: api.mykratos.v1.ListMyReply
}
var file_api_mykratos_v1_my_proto_depIdxs = []int32{
	0,  // 0: api.mykratos.v1.CreateMyReply.MyContent:type_name -> api.mykratos.v1.MyContent
	0,  // 1: api.mykratos.v1.UpdateMyReply.MyContent:type_name -> api.mykratos.v1.MyContent
	0,  // 2: api.mykratos.v1.GetMyReply.MyContent:type_name -> api.mykratos.v1.MyContent
	0,  // 3: api.mykratos.v1.ListMyReply.results:type_name -> api.mykratos.v1.MyContent
	1,  // 4: api.mykratos.v1.My.CreateMy:input_type -> api.mykratos.v1.CreateMyRequest
	3,  // 5: api.mykratos.v1.My.UpdateMy:input_type -> api.mykratos.v1.UpdateMyRequest
	5,  // 6: api.mykratos.v1.My.DeleteMy:input_type -> api.mykratos.v1.DeleteMyRequest
	7,  // 7: api.mykratos.v1.My.GetMy:input_type -> api.mykratos.v1.GetMyRequest
	9,  // 8: api.mykratos.v1.My.ListMy:input_type -> api.mykratos.v1.ListMyRequest
	2,  // 9: api.mykratos.v1.My.CreateMy:output_type -> api.mykratos.v1.CreateMyReply
	4,  // 10: api.mykratos.v1.My.UpdateMy:output_type -> api.mykratos.v1.UpdateMyReply
	6,  // 11: api.mykratos.v1.My.DeleteMy:output_type -> api.mykratos.v1.DeleteMyReply
	8,  // 12: api.mykratos.v1.My.GetMy:output_type -> api.mykratos.v1.GetMyReply
	10, // 13: api.mykratos.v1.My.ListMy:output_type -> api.mykratos.v1.ListMyReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_mykratos_v1_my_proto_init() }
func file_api_mykratos_v1_my_proto_init() {
	if File_api_mykratos_v1_my_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mykratos_v1_my_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mykratos_v1_my_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mykratos_v1_my_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mykratos_v1_my_proto_goTypes,
		DependencyIndexes: file_api_mykratos_v1_my_proto_depIdxs,
		MessageInfos:      file_api_mykratos_v1_my_proto_msgTypes,
	}.Build()
	File_api_mykratos_v1_my_proto = out.File
	file_api_mykratos_v1_my_proto_rawDesc = nil
	file_api_mykratos_v1_my_proto_goTypes = nil
	file_api_mykratos_v1_my_proto_depIdxs = nil
}
