// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"kratos-m/internal/biz"
	"kratos-m/internal/conf"
	"kratos-m/internal/data"
	"kratos-m/internal/server"
	"kratos-m/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)

	myRepo := data.NewMyRepo(dataData,logger)
	myUseCase := biz.NewMyUseCase(myRepo,logger)
	mService := service.NewMyService(myUseCase)

	httpServer := server.NewHTTPServer(confServer, logger,greeterService,mService)
	grpcServer := server.NewGRPCServer(confServer, logger,greeterService,mService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
